version: '3'
services:
  api:
    build:
      context: api
    depends_on:
      - elastic
      - redis
    environment:
      - REDIS_HOST
      - ELASTIC_SCHEMA
      - ELASTIC_HOST
      - ELASTIC_PORT
      - APP_HOST=${API_HOST}
      - APP_PORT=${API_PORT}
    volumes:
      - ./api:/app

  admin-panel:
    image: agorobets/admin-panel:latest
    environment:
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - SECRET_KEY
      - DEBUG
    volumes:
      - admin-panel-static:/app/static
    depends_on:
      - postgres

  postgres:
    image: agorobets/admin-panel-postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  indexer:
    build:
      context: api
    depends_on:
      - postgres
      - elastic
      - redis
    environment:
      - REDIS_HOST
      - ELASTIC_SCHEMA
      - ELASTIC_HOST
      - ELASTIC_PORT
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    volumes:
      - ./api:/app
    command: make index

  elastic:
    build:
      context: elastic
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - "9200:9200"

  redis:
    image: redis:7.0.0-alpine

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - admin-panel-static:/data/static
    depends_on:
      - admin-panel
      - api
    ports:
      - "80:80"
volumes:
  admin-panel-static:
