services:
  elastic:
    # dev config can map/access directly to/from host
    ports:
      - 127.0.0.1:$ELASTIC_PORT:$ELASTIC_PORT

  redis:
    # dev config can map/access directly to/from host
    ports:
      - 127.0.0.1:$REDIS_PORT:$REDIS_PORT

  api:
    # dev config can map/access directly to/from host
    ports:
      - 127.0.0.1:$API_PORT:$API_PORT

  tests:
    # dev config also runs tests next to running api
    # using default api container image, from git project name
    image: async_api_sprint_1_api
    command: make dev
    depends_on:
      - api
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - ELASTIC_SCHEMA
      - ELASTIC_HOST
      - ELASTIC_PORT
      - API_HOST
      - API_PORT
      - DEBUG
    volumes:
      - ./api:/app
